
AWSTemplateFormatVersion: '2010-09-09'
Description: s3-bucket CloudFormation Template

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - qa
      - test

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::Region}-my-s3-bucket-${Environment}"

      VersioningConfiguration:
        Status: Enabled

      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true

      LifecycleConfiguration:
        Rules:
          - Id: TransitionRule
            Status: Enabled
            Transitions:
              - StorageClass: STANDARD_IA
                TransitionInDays: 30
              - StorageClass: GLACIER
                TransitionInDays: 60
            ExpirationInDays: 365

          - Id: NonCurrentVersionCleanup
            Status: Enabled
            NoncurrentVersionExpiration:
              NoncurrentDays: 90

      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

      Tags:
        - Key: Environment
          Value: !Ref Environment

        - Key: Name
          Value: !Sub "my-s3-bucket-${AWS::Region}-${AWS::AccountId}"

  MyS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MyS3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: EnforceSSL
            Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource:
              - !Sub "${MyS3Bucket.Arn}"
              - !Sub "${MyS3Bucket.Arn}/*"
            Condition:
              Bool:
                aws:SecureTransport: false

          - Sid: AllowAccountAccess
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "s3:*"
            Resource:
              - !Sub "${MyS3Bucket.Arn}"
              - !Sub "${MyS3Bucket.Arn}/*"

Outputs:
  S3BucketName:
    Description: Bucket Name
    Value: !Ref MyS3Bucket

  S3BucketArn:
    Description: Bucket ARN
    Value: !GetAtt MyS3Bucket.Arn
